// vault-portal/src/app/admin/reports/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle, Undo2 } from "lucide-react";
import { useAuth } from "@/lib/auth";
import PageHeader from "@/components/PageHeader";
import Skeleton from "@/components/Skeleton";

interface ReportItem {
  id: number;
  targetType: string;
  targetId: number;
  targetTitle?: string | null;
  reason: string;
  reporter?: string | null;
  status: string;
  createdAt: string;
}

const TARGET_LABELS: Record<string, string> = {
  tool: "工具",
  prompt: "提示词",
  article: "文章",
  news: "资讯",
  repo: "开源",
  resource: "资源",
  mcp: "MCP",
  post: "帖子",
};

export default function AdminReportsPage() {
  const router = useRouter();
  const { user } = useAuth();
  const [items, setItems] = useState<ReportItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("open");
  const [busyId, setBusyId] = useState<number | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(
        `/api/reports?limit=50${filter !== "all" ? `&status=${filter}` : ""}`,
      );
      if (res.ok) {
        const data = await res.json();
        setItems(Array.isArray(data) ? data : data.items ?? []);
      }
    } catch {
      // 保持旧列表
    } finally {
      setLoading(false);
    }
  }, [filter]);

  useEffect(() => {
    if (!user) {
      router.push("/login");
      return;
    }
    if (user.role !== "admin") {
      router.push("/");
      return;
    }
    void (async () => {
      await load();
    })();
  }, [user, load, router]);

  const handleResolve = async (id: number, status: "open" | "resolved") => {
    setBusyId(id);
    try {
      const res = await fetch(`/api/reports/${id}/status`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status }),
      });
      if (!res.ok) {
        window.alert("操作失败，请重试。");
        return;
      }
      await load();
    } finally {
      setBusyId(null);
    }
  };

  if (user?.role !== "admin") return null;

  return (
    <div className="space-y-6">
      <PageHeader
        title="举报管理"
        description="处理用户对内容的举报，核实后标记完成。"
      />

      <div className="flex flex-wrap gap-2">
        {[
          ["open", "待处理"],
          ["resolved", "已处理"],
          ["all", "全部"],
        ].map(([v, l]) => (
          <button
            key={v}
            onClick={() => setFilter(v)}
            className={`rounded-full px-3 py-1 text-xs font-medium transition ${
              filter === v
                ? "bg-[#1677ff] text-white"
                : "bg-white text-zinc-600 ring-1 ring-zinc-200 hover:bg-zinc-50 dark:bg-zinc-900 dark:text-zinc-300 dark:ring-zinc-700"
            }`}
          >
            {l}
          </button>
        ))}
      </div>

      {loading ? (
        <div className="space-y-3">
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className="h-16" />
          ))}
        </div>
      ) : items.length === 0 ? (
        <p className="rounded-xl border border-dashed border-zinc-200 py-10 text-center text-sm text-zinc-400 dark:border-zinc-800">
          暂无举报记录。
        </p>
      ) : (
        <div className="space-y-2">
          {items.map((r) => (
            <div
              key={r.id}
              className="flex items-center justify-between gap-4 rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"
            >
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-2 text-sm">
                  <span className="rounded-md bg-zinc-100 px-2 py-0.5 text-[11px] text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300">
                    {TARGET_LABELS[r.targetType] ?? r.targetType}
                  </span>
                  <span className="truncate font-medium text-zinc-900 dark:text-zinc-50">
                    {r.targetTitle || `#${r.targetId}`}
                  </span>
                  {r.status === "resolved" && (
                    <span className="rounded-md bg-emerald-50 px-2 py-0.5 text-[11px] text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-400">
                      已处理
                    </span>
                  )}
                </div>
                <p className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">
                  举报原因：{r.reason}
                  {r.reporter ? ` · 举报人 @${r.reporter}` : ""}
                </p>
              </div>
              <div className="flex shrink-0 gap-2">
                {r.status === "open" ? (
                  <button
                    onClick={() => handleResolve(r.id, "resolved")}
                    disabled={busyId === r.id}
                    className="inline-flex items-center gap-1 rounded-lg bg-emerald-500 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-emerald-600 disabled:opacity-50"
                  >
                    <CheckCircle size={13} /> 标记已处理
                  </button>
                ) : (
                  <button
                    onClick={() => handleResolve(r.id, "open")}
                    disabled={busyId === r.id}
                    className="inline-flex items-center gap-1 rounded-lg border border-zinc-200 px-3 py-1.5 text-xs text-zinc-600 transition hover:border-[#1677ff]/40 hover:text-[#1677ff] disabled:opacity-50 dark:border-zinc-700 dark:text-zinc-300"
                  >
                    <Undo2 size={13} /> 重新打开
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ai-portal-admin/src/views/reports/index.vue
<script setup lang="ts">
import { ref, onMounted, watch } from "vue";
import { message } from "@/utils/message";
import {
  getReports,
  updateReportStatus,
  errMsg,
  type ReportItem
} from "@/api/admin";

defineOptions({ name: "Reports" });

const LIMIT = 20;

const TARGET_LABELS: Record<string, string> = {
  tool: "工具",
  prompt: "提示词",
  article: "文章",
  news: "资讯",
  repo: "开源",
  resource: "资源",
  mcp: "MCP",
  post: "帖子"
};

const items = ref<ReportItem[]>([]);
const page = ref(1);
const filter = ref("open");
const loading = ref(false);
const busyId = ref<number | null>(null);

const pagedItems = ref<ReportItem[]>([]);

async function load() {
  loading.value = true;
  try {
    const data = await getReports(filter.value);
    items.value = Array.isArray(data) ? data : (data.items ?? []);
    page.value = 1;
    slicePage();
  } catch {
    // 保持旧列表
  } finally {
    loading.value = false;
  }
}

function slicePage() {
  pagedItems.value = items.value.slice((page.value - 1) * LIMIT, page.value * LIMIT);
}

watch(page, slicePage);

async function setStatus(item: ReportItem, status: "open" | "resolved") {
  busyId.value = item.id;
  try {
    await updateReportStatus(item.id, status);
    message(status === "resolved" ? "已标记处理" : "已重新打开", {
      type: "success"
    });
    await load();
  } catch (e) {
    message(errMsg(e, "操作失败"), { type: "error" });
  } finally {
    busyId.value = null;
  }
}

function fmtTime(t?: string) {
  return t ? new Date(t).toLocaleString("zh-CN") : "—";
}

onMounted(load);
watch(filter, load);
</script>

<template>
  <div class="p-5">
    <div class="mb-4">
      <h2 class="text-lg font-semibold">举报管理</h2>
      <p class="mt-1 text-sm text-[var(--el-text-color-secondary)]">
        处理用户对内容的举报，核实后标记完成。
      </p>
    </div>

    <div class="mb-4">
      <el-radio-group v-model="filter" size="small">
        <el-radio-button value="open">待处理</el-radio-button>
        <el-radio-button value="resolved">已处理</el-radio-button>
        <el-radio-button value="all">全部</el-radio-button>
      </el-radio-group>
    </div>

    <el-card shadow="never" :body-style="{ padding: 0 }">
      <el-table v-loading="loading" :data="pagedItems" stripe style="width: 100%">
        <el-table-column label="目标" min-width="200">
          <template #default="{ row }">
            <div class="flex items-center gap-2">
              <el-tag size="small" type="info">
                {{ TARGET_LABELS[row.targetType] ?? row.targetType }}
              </el-tag>
              <span class="truncate font-medium">
                {{ row.targetTitle || `#${row.targetId}` }}
              </span>
            </div>
          </template>
        </el-table-column>
        <el-table-column label="举报原因" min-width="220">
          <template #default="{ row }">
            <span class="line-clamp-2 text-sm text-[var(--el-text-color-regular)]">
              {{ row.reason }}
            </span>
          </template>
        </el-table-column>
        <el-table-column label="举报人" width="120">
          <template #default="{ row }">
            <span class="text-[var(--el-text-color-secondary)]">
              {{ row.reporter ? "@" + row.reporter : "—" }}
            </span>
          </template>
        </el-table-column>
        <el-table-column label="状态" width="100">
          <template #default="{ row }">
            <el-tag size="small" :type="row.status === 'resolved' ? 'success' : 'warning'">
              {{ row.status === "resolved" ? "已处理" : "待处理" }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="时间" width="170">
          <template #default="{ row }">
            <span class="text-xs text-[var(--el-text-color-secondary)]">
              {{ fmtTime(row.createdAt) }}
            </span>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="130" align="right" fixed="right">
          <template #default="{ row }">
            <el-button
              v-if="row.status === 'open'"
              link
              type="success"
              size="small"
              :disabled="busyId === row.id"
              @click="setStatus(row as ReportItem, 'resolved')"
            >
              标记已处理
            </el-button>
            <el-button
              v-else
              link
              type="primary"
              size="small"
              :disabled="busyId === row.id"
              @click="setStatus(row as ReportItem, 'open')"
            >
              重新打开
            </el-button>
          </template>
        </el-table-column>
        <template #empty>
          <el-empty description="暂无举报记录。" :image-size="80" />
        </template>
      </el-table>
      <div class="flex items-center justify-between p-3">
        <span class="text-xs text-[var(--el-text-color-secondary)]">
          共 {{ items.length }} 条
        </span>
        <el-pagination
          v-model:current-page="page"
          background
          layout="prev, pager, next"
          :total="items.length"
          :page-size="LIMIT"
        />
      </div>
    </el-card>
  </div>
</template>
