// vault-portal-admin/src/views/review/index.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from "vue";
import { message } from "@/utils/message";
import { ElMessageBox } from "element-plus";
import {
  getReviewList,
  reviewOne,
  reviewBatch,
  errMsg,
  type ReviewItem,
  type ReviewStatus,
  type ReviewType
} from "@/api/admin";

defineOptions({ name: "Review" });

const TYPE_META: Record<ReviewType, { label: string; titleField: "name" | "title" }> = {
  news: { label: "资讯", titleField: "title" },
  tool: { label: "工具", titleField: "name" },
  prompt: { label: "提示词", titleField: "title" },
  github: { label: "GitHub", titleField: "name" },
  knowledge: { label: "知识库", titleField: "title" },
  mcp: { label: "MCP", titleField: "name" },
  resource: { label: "学习资源", titleField: "title" }
};

const TYPE_KEYS = Object.keys(TYPE_META) as ReviewType[];

const PAGE_SIZE = 20;

const type = ref<ReviewType>("news");
// 状态页签：pending=待审核（先审后发模式用）；published=已发布（可下架）；rejected=已拒绝
// 采集内容默认免审直发（CRAWLER_AUTO_PUBLISH），日常主要在「已发布」页签做下架
const statusFilter = ref<ReviewStatus>("pending");
const STATUS_META: Record<ReviewStatus, { label: string }> = {
  pending: { label: "待审核" },
  published: { label: "已发布" },
  rejected: { label: "已拒绝" }
};
const STATUS_KEYS = Object.keys(STATUS_META) as ReviewStatus[];
const items = ref<ReviewItem[]>([]);
const loading = ref(false);
const busyId = ref<number | null>(null);
const bulkBusy = ref(false);
const page = ref(1);

const tableRef = ref<{ clearSelection: () => void }>();
const selectedRows = ref<ReviewItem[]>([]);

const detailOpen = ref(false);
const detailItem = ref<ReviewItem | null>(null);

const meta = computed(() => TYPE_META[type.value]);
const statusMeta = computed(() => STATUS_META[statusFilter.value]);
// 拒绝动作在「已发布」页签语义为下架
const rejectVerb = computed(() =>
  statusFilter.value === "published" ? "下架" : "拒绝"
);
const selectedIds = computed(() => selectedRows.value.map(r => r.id));
const pagedItems = computed(() =>
  items.value.slice((page.value - 1) * PAGE_SIZE, page.value * PAGE_SIZE)
);

const titleOf = (item: ReviewItem) =>
  item[meta.value.titleField] ?? item.title ?? item.name ?? item.slug;
const summaryOf = (item: ReviewItem) => item.description ?? item.summary ?? "";

async function load() {
  loading.value = true;
  try {
    const data = await getReviewList(type.value, statusFilter.value);
    items.value = Array.isArray(data) ? data : [];
    // 数据刷新后当前页可能越界（如批量通过后队列清空）
    if ((page.value - 1) * PAGE_SIZE >= items.value.length) page.value = 1;
  } catch (e) {
    message(errMsg(e, "加载失败"), { type: "error" });
    items.value = [];
  } finally {
    loading.value = false;
  }
}

function onSelectionChange(rows: ReviewItem[]) {
  selectedRows.value = rows;
}

function clearSelection() {
  tableRef.value?.clearSelection();
  selectedRows.value = [];
}

async function review(id: number, action: "approve" | "reject") {
  busyId.value = id;
  try {
    await reviewOne(type.value, id, action);
    message(action === "approve" ? "已通过" : `已${rejectVerb.value}`, {
      type: "success"
    });
    await load();
  } catch (e) {
    message(errMsg(e, "操作失败"), { type: "error" });
  } finally {
    busyId.value = null;
  }
}

/** 详情弹窗内的单条审核，成功后关闭弹窗 */
async function reviewFromDetail(action: "approve" | "reject") {
  if (!detailItem.value) return;
  const id = detailItem.value.id;
  await review(id, action);
  detailOpen.value = false;
}

function openDetail(item: ReviewItem) {
  detailItem.value = item;
  detailOpen.value = true;
}

/**
 * 批量审核。scope=selected 只处理勾选项（row-key + reserve-selection 支持
 * 跨页保留勾选）；scope=all 处理该类型全部待审（后端单次上限 500，剩余可再点）。
 */
async function runBulk(action: "approve" | "reject", scope: "selected" | "all") {
  const ids = scope === "selected" ? selectedIds.value : undefined;
  if (scope === "selected" && ids.length === 0) return;

  const verb = action === "approve" ? "通过" : rejectVerb.value;
  const target =
    scope === "all"
      ? `当前${statusMeta.value.label}的全部${meta.value.label}（每次最多 500 条）`
      : `选中的 ${ids.length} 条${meta.value.label}`;
  try {
    await ElMessageBox.confirm(`确认${verb}${target}？`, "批量审核", {
      type: "warning",
      confirmButtonText: verb,
      cancelButtonText: "取消"
    });
  } catch {
    return;
  }

  bulkBusy.value = true;
  try {
    // scope=all 按当前状态页签圈定范围（后端按 status 查询后批量翻转）
    const res = await reviewBatch(
      type.value,
      action,
      ids,
      scope === "all" ? statusFilter.value : undefined
    );
    clearSelection();
    await load();
    if (res.remaining > 0) {
      message(
        `本次${verb} ${res.updated} 条，还剩 ${res.remaining} 条，可再次点击「全部${verb}」继续。`,
        { type: "info", duration: 5000 }
      );
    }
  } catch (e) {
    message(errMsg(e, "批量操作失败"), { type: "error" });
  } finally {
    bulkBusy.value = false;
  }
}

onMounted(load);
watch(type, () => {
  // 切换内容类型时清空选择并回到第一页，避免把上一类的 id 带过去
  clearSelection();
  page.value = 1;
  load();
});
watch(statusFilter, () => {
  clearSelection();
  page.value = 1;
  load();
});
</script>

<template>
  <div class="p-5">
    <div class="mb-4">
      <h2 class="text-lg font-semibold">采集审核</h2>
      <p class="mt-1 text-sm text-[var(--el-text-color-secondary)]">
        采集内容默认免审自动发布；在「已发布」页签可下架违规内容。设环境变量
        CRAWLER_AUTO_PUBLISH=false 可恢复「先审后发」模式。
      </p>
    </div>

    <!-- 筛选行：类型切换 + 状态页签 + 批量操作 -->
    <div class="mb-4 flex flex-wrap items-center justify-between gap-3">
      <div class="flex flex-wrap items-center gap-3">
        <el-radio-group v-model="type" size="small">
          <el-radio-button v-for="k in TYPE_KEYS" :key="k" :value="k">
            {{ TYPE_META[k].label }}
          </el-radio-button>
        </el-radio-group>
        <el-radio-group v-model="statusFilter" size="small">
          <el-radio-button v-for="s in STATUS_KEYS" :key="s" :value="s">
            {{ STATUS_META[s].label }}
          </el-radio-button>
        </el-radio-group>
      </div>
      <div class="flex flex-wrap items-center gap-2">
        <template v-if="statusFilter === 'pending'">
          <el-button
            size="small"
            type="success"
            :disabled="bulkBusy || selectedIds.length === 0"
            @click="runBulk('approve', 'selected')"
          >
            通过所选（{{ selectedIds.length }}）
          </el-button>
          <el-button
            size="small"
            type="danger"
            plain
            :disabled="bulkBusy || selectedIds.length === 0"
            @click="runBulk('reject', 'selected')"
          >
            拒绝所选
          </el-button>
          <el-divider direction="vertical" />
          <el-button
            size="small"
            type="success"
            plain
            :disabled="bulkBusy"
            @click="runBulk('approve', 'all')"
          >
            全部通过
          </el-button>
          <el-button
            size="small"
            type="danger"
            plain
            :disabled="bulkBusy"
            @click="runBulk('reject', 'all')"
          >
            全部拒绝
          </el-button>
        </template>
        <template v-else-if="statusFilter === 'published'">
          <el-button
            size="small"
            type="danger"
            plain
            :disabled="bulkBusy || selectedIds.length === 0"
            @click="runBulk('reject', 'selected')"
          >
            下架所选（{{ selectedIds.length }}）
          </el-button>
          <el-divider direction="vertical" />
          <el-button
            size="small"
            type="danger"
            plain
            :disabled="bulkBusy"
            @click="runBulk('reject', 'all')"
          >
            全部下架
          </el-button>
        </template>
      </div>
    </div>

    <el-card shadow="never" :body-style="{ padding: 0 }">
      <el-table
        ref="tableRef"
        v-loading="loading"
        :data="pagedItems"
        row-key="id"
        stripe
        style="width: 100%"
        @selection-change="onSelectionChange"
      >
        <el-table-column type="selection" width="45" reserve-selection />
        <el-table-column label="标题" min-width="240">
          <template #default="{ row }">
            <div class="flex items-center gap-2">
              <el-tag size="small" type="info">{{ meta.label }}</el-tag>
              <a
                class="cursor-pointer font-medium hover:text-[var(--el-color-primary)]"
                @click="openDetail(row as ReviewItem)"
              >
                {{ titleOf(row as ReviewItem) }}
              </a>
              <span class="text-xs text-[var(--el-text-color-secondary)]">
                #{{ row.id }}
              </span>
            </div>
          </template>
        </el-table-column>
        <el-table-column label="摘要" min-width="300">
          <template #default="{ row }">
            <span class="line-clamp-2 text-sm text-[var(--el-text-color-secondary)]">
              {{ summaryOf(row as ReviewItem) || "—" }}
            </span>
          </template>
        </el-table-column>
        <el-table-column label="采集时间" width="170">
          <template #default="{ row }">
            <span class="text-xs text-[var(--el-text-color-secondary)]">
              {{ row.createdAt ? new Date(row.createdAt).toLocaleString("zh-CN") : "—" }}
            </span>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="210" align="right" fixed="right">
          <template #default="{ row }">
            <el-button
              link
              type="primary"
              size="small"
              @click="openDetail(row as ReviewItem)"
            >
              查看详情
            </el-button>
            <el-button
              v-if="statusFilter === 'pending'"
              link
              type="success"
              size="small"
              :disabled="busyId === row.id || bulkBusy"
              @click="review(row.id, 'approve')"
            >
              通过
            </el-button>
            <el-button
              v-if="statusFilter !== 'rejected'"
              link
              type="danger"
              size="small"
              :disabled="busyId === row.id || bulkBusy"
              @click="review(row.id, 'reject')"
            >
              {{ rejectVerb }}
            </el-button>
          </template>
        </el-table-column>
        <template #empty>
          <el-empty
            :description="`暂无${statusMeta.label}的${meta.label}内容`"
            :image-size="80"
          />
        </template>
      </el-table>
      <div class="flex items-center justify-between p-3">
        <span class="text-xs text-[var(--el-text-color-secondary)]">
          共 {{ items.length }} 条{{ statusMeta.label }}
        </span>
        <el-pagination
          v-model:current-page="page"
          background
          layout="prev, pager, next"
          :total="items.length"
          :page-size="PAGE_SIZE"
        />
      </div>
    </el-card>

    <!-- 详情弹窗 -->
    <el-dialog
      v-model="detailOpen"
      :title="`详情 · ${meta.label}`"
      width="640px"
      destroy-on-close
    >
      <template v-if="detailItem">
        <div class="mb-3 flex flex-wrap items-center gap-2">
          <el-tag size="small" type="info">{{ meta.label }}</el-tag>
          <span class="text-xs text-[var(--el-text-color-secondary)]">
            #{{ detailItem.id }}
          </span>
          <span
            v-if="detailItem.slug"
            class="text-xs text-[var(--el-text-color-secondary)]"
          >
            slug: {{ detailItem.slug }}
          </span>
          <span
            v-if="detailItem.createdAt"
            class="text-xs text-[var(--el-text-color-secondary)]"
          >
            {{ new Date(detailItem.createdAt).toLocaleString("zh-CN") }}
          </span>
        </div>

        <h4 class="mb-2 text-base font-semibold">{{ titleOf(detailItem) }}</h4>

        <p
          v-if="summaryOf(detailItem)"
          class="mb-3 text-sm text-[var(--el-text-color-regular)]"
        >
          {{ summaryOf(detailItem) }}
        </p>

        <div
          v-if="detailItem.content"
          class="max-h-[45vh] overflow-y-auto rounded-lg bg-[var(--el-fill-color-light)] p-3 text-sm leading-relaxed whitespace-pre-wrap text-[var(--el-text-color-regular)]"
        >
          {{ detailItem.content }}
        </div>

        <a
          v-if="detailItem.url"
          :href="detailItem.url"
          target="_blank"
          rel="noopener noreferrer"
          class="mt-3 inline-block break-all text-xs text-[var(--el-color-primary)] hover:underline"
        >
          {{ detailItem.url }}
        </a>
      </template>
      <template #footer>
        <el-button @click="detailOpen = false">关闭</el-button>
        <el-button
          v-if="statusFilter !== 'rejected'"
          type="danger"
          plain
          :disabled="busyId === detailItem?.id"
          @click="reviewFromDetail('reject')"
        >
          {{ rejectVerb }}
        </el-button>
        <el-button
          v-if="statusFilter === 'pending'"
          type="success"
          :disabled="busyId === detailItem?.id"
          @click="reviewFromDetail('approve')"
        >
          通过
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

// ai-portal/src/app/admin/review/page.tsx
"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  CheckCircle,
  XCircle,
  Clock,
  ArrowRight,
  Wrench,
  MessageSquare,
  Newspaper,
  FolderOpen,
  GitBranch,
  CheckCheck,
  XOctagon,
  Server,
  BookOpen,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import Skeleton from "@/components/Skeleton";
import { useAuth } from "@/lib/auth";
import { adminFetch } from "@/lib/admin";

interface QueueItem {
  id: number;
  slug: string;
  name?: string;
  title?: string;
  description?: string;
  summary?: string;
  content?: string;
  url?: string;
  status: string;
  createdAt?: string;
}

interface TypeMeta {
  label: string;
  icon: LucideIcon;
  titleField: "title" | "name";
  color: string;
}

const TYPE_META: Record<string, TypeMeta> = {
  news: { label: "资讯", icon: Newspaper, titleField: "title", color: "text-orange-500 bg-orange-50 dark:bg-orange-500/10" },
  tool: { label: "工具", icon: Wrench, titleField: "name", color: "text-[#1677ff] bg-[#1677ff]/10 dark:bg-blue-500/10" },
  prompt: { label: "提示词", icon: MessageSquare, titleField: "title", color: "text-emerald-500 bg-emerald-50 dark:bg-emerald-500/10" },
  github: { label: "GitHub", icon: GitBranch, titleField: "name", color: "text-zinc-600 bg-zinc-100 dark:bg-zinc-800 dark:text-zinc-300" },
  knowledge: { label: "知识库", icon: FolderOpen, titleField: "title", color: "text-amber-500 bg-amber-50 dark:bg-amber-500/10" },
  mcp: { label: "MCP", icon: Server, titleField: "name", color: "text-cyan-600 bg-cyan-50 dark:bg-cyan-500/10" },
  resource: { label: "学习资源", icon: BookOpen, titleField: "title", color: "text-violet-600 bg-violet-50 dark:bg-violet-500/10" },
};

const TYPE_KEYS = Object.keys(TYPE_META);

interface BatchResult {
  updated: number;
  remaining: number;
}

export default function AdminReviewPage() {
  const router = useRouter();
  const { user } = useAuth();

  const [type, setType] = useState("news");
  const [items, setItems] = useState<QueueItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<number | null>(null);
  const [bulkBusy, setBulkBusy] = useState(false);
  const [selected, setSelected] = useState<Set<number>>(new Set());
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (user && user.role !== "admin") router.replace("/");
  }, [user, router]);

  // 切换内容类型时清空选择，避免把上一类的 id 带过去
  useEffect(() => {
    void (async () => {
      setSelected(new Set());
    })();
  }, [type]);

  const load = useCallback(async () => {
    if (!user) return;
    setLoading(true);
    setError(null);
    try {
      const data = await adminFetch<QueueItem[]>(
        `/crawler/review/${type}?status=pending`,
      );
      setItems(Array.isArray(data) ? data : []);
    } catch (e) {
      setError(e instanceof Error ? e.message : "加载失败");
      setItems([]);
    } finally {
      setLoading(false);
    }
  }, [user, type]);

  useEffect(() => {
    void (async () => {
      if (user?.role === "admin") await load();
    })();
  }, [load, user]);

  const review = async (id: number, action: "approve" | "reject") => {
    setBusyId(id);
    try {
      await adminFetch(`/crawler/review/${type}/${id}/${action}`, {
        method: "PATCH",
      });
      setSelected((prev) => {
        const next = new Set(prev);
        next.delete(id);
        return next;
      });
      load();
    } catch (e) {
      alert(e instanceof Error ? e.message : "操作失败");
    } finally {
      setBusyId(null);
    }
  };

  const allSelected = items.length > 0 && selected.size === items.length;

  const toggleOne = (id: number) => {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const toggleAll = () => {
    setSelected(allSelected ? new Set() : new Set(items.map((i) => i.id)));
  };

  /**
   * 批量审核。scope=selected 只处理勾选项；scope=all 处理该类型全部待审
   * （后端单次上限 500，剩余部分可再次点击继续）。
   */
  const runBulk = async (action: "approve" | "reject", scope: "selected" | "all") => {
    const ids = scope === "selected" ? Array.from(selected) : undefined;
    if (scope === "selected" && (!ids || ids.length === 0)) return;

    const verb = action === "approve" ? "通过" : "拒绝";
    const target =
      scope === "all"
        ? `当前全部待审的${meta.label}（每次最多 500 条）`
        : `选中的 ${ids!.length} 条${meta.label}`;
    if (!window.confirm(`确认${verb}${target}？`)) return;

    setBulkBusy(true);
    try {
      const res = await adminFetch<BatchResult>(`/crawler/review/${type}/batch`, {
        method: "POST",
        body: JSON.stringify({ action, ids }),
      });
      setSelected(new Set());
      await load();
      if (res.remaining > 0) {
        alert(
          `本次${verb} ${res.updated} 条，队列还剩 ${res.remaining} 条待审，可再次点击「全部${verb}」继续。`,
        );
      }
    } catch (e) {
      alert(e instanceof Error ? e.message : "批量操作失败");
    } finally {
      setBulkBusy(false);
    }
  };

  const meta = TYPE_META[type];
  const titleOf = useMemo(
    () => (item: QueueItem) =>
      (meta.titleField === "name" ? item.name : item.title) ??
      item.title ??
      item.name ??
      item.slug,
    [meta.titleField],
  );

  if (user?.role !== "admin") return null;

  return (
    <div className="space-y-6">
      <PageHeader title="审核中心" description="处理用户投稿与采集内容的发布审核。" />

      {/* 用户投稿入口 */}
      <Link
        href="/admin/submissions"
        className="flex items-center justify-between rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm transition hover:border-[#1677ff]/30 dark:border-zinc-800 dark:bg-zinc-900 dark:hover:border-[#5aa0ff]/40"
      >
        <div>
          <h3 className="text-base font-semibold text-zinc-900 dark:text-zinc-50">
            用户投稿审核
          </h3>
          <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
            用户提交的工具、提示词、MCP、资源、资讯，审核通过后自动发布
          </p>
        </div>
        <ArrowRight size={18} className="shrink-0 text-zinc-400" />
      </Link>

      {/* 采集内容审核 */}
      <div className="rounded-2xl border border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-100 px-5 py-4 dark:border-zinc-800">
          <h3 className="text-base font-semibold text-zinc-900 dark:text-zinc-50">
            采集内容审核
          </h3>
          <div className="flex flex-wrap gap-2">
            {TYPE_KEYS.map((k) => (
              <button
                key={k}
                onClick={() => setType(k)}
                className={`rounded-full px-3 py-1 text-xs font-medium transition ${
                  type === k
                    ? "bg-[#1677ff] text-white"
                    : "bg-white text-zinc-600 ring-1 ring-zinc-200 hover:bg-zinc-50 dark:bg-zinc-900 dark:text-zinc-300 dark:ring-zinc-700"
                }`}
              >
                {TYPE_META[k].label}
              </button>
            ))}
          </div>
        </div>

        {error && (
          <div className="border-b border-zinc-100 px-5 py-3 text-sm text-rose-600 dark:border-zinc-800 dark:text-rose-400">
            {error}
          </div>
        )}

        {loading ? (
          <div className="space-y-3 p-5">
            {Array.from({ length: 4 }).map((_, i) => (
              <Skeleton key={i} className="h-20" />
            ))}
          </div>
        ) : items.length === 0 ? (
          <div className="py-14 text-center">
            <Clock size={28} className="mx-auto text-zinc-300 dark:text-zinc-600" />
            <p className="mt-3 text-sm text-zinc-500 dark:text-zinc-400">
              暂无待审核的{meta.label}内容
            </p>
          </div>
        ) : (
          <>
            {/* 批量操作条 */}
            <div className="flex flex-wrap items-center justify-between gap-3 border-b border-zinc-100 bg-zinc-50/70 px-5 py-3 dark:border-zinc-800 dark:bg-zinc-900/50">
              <label className="flex items-center gap-2 text-sm text-zinc-600 dark:text-zinc-300">
                <input
                  type="checkbox"
                  checked={allSelected}
                  onChange={toggleAll}
                  className="h-4 w-4 rounded border-zinc-300 accent-[#1677ff] dark:border-zinc-600"
                />
                全选（本页 {items.length} 条待审
                {selected.size > 0 && ` · 已选 ${selected.size}`}）
              </label>
              <div className="flex flex-wrap gap-2">
                <button
                  onClick={() => runBulk("approve", "selected")}
                  disabled={bulkBusy || selected.size === 0}
                  className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-emerald-500 disabled:cursor-not-allowed disabled:opacity-40"
                >
                  <CheckCircle size={13} /> 通过所选
                </button>
                <button
                  onClick={() => runBulk("reject", "selected")}
                  disabled={bulkBusy || selected.size === 0}
                  className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-1.5 text-xs font-medium text-red-600 transition hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-40 dark:border-red-500/30 dark:hover:bg-red-500/10"
                >
                  <XCircle size={13} /> 拒绝所选
                </button>
                <span className="mx-1 hidden w-px self-stretch bg-zinc-200 sm:block dark:bg-zinc-700" />
                <button
                  onClick={() => runBulk("approve", "all")}
                  disabled={bulkBusy}
                  className="inline-flex items-center gap-1 rounded-lg border border-emerald-300 px-3 py-1.5 text-xs font-medium text-emerald-700 transition hover:bg-emerald-50 disabled:cursor-not-allowed disabled:opacity-40 dark:border-emerald-500/40 dark:text-emerald-400 dark:hover:bg-emerald-500/10"
                >
                  <CheckCheck size={13} /> 全部通过
                </button>
                <button
                  onClick={() => runBulk("reject", "all")}
                  disabled={bulkBusy}
                  className="inline-flex items-center gap-1 rounded-lg border border-red-300 px-3 py-1.5 text-xs font-medium text-red-700 transition hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-40 dark:border-red-500/40 dark:text-red-400 dark:hover:bg-red-500/10"
                >
                  <XOctagon size={13} /> 全部拒绝
                </button>
              </div>
            </div>

            <div className="space-y-3 p-5">
              {items.map((item) => {
                const title = titleOf(item);
                const TypeIcon = meta.icon;
                const checked = selected.has(item.id);
                return (
                  <div
                    key={item.id}
                    className={`flex items-start justify-between gap-4 rounded-xl border p-4 transition ${
                      checked
                        ? "border-[#1677ff]/40 bg-[#1677ff]/5 dark:border-[#5aa0ff]/40 dark:bg-[#1677ff]/5"
                        : "border-zinc-100 dark:border-zinc-800"
                    }`}
                  >
                    <div className="flex min-w-0 gap-3">
                      <input
                        type="checkbox"
                        checked={checked}
                        onChange={() => toggleOne(item.id)}
                        aria-label={`选择 #${item.id}`}
                        className="mt-1 h-4 w-4 shrink-0 rounded border-zinc-300 accent-[#1677ff] dark:border-zinc-600"
                      />
                      <div className="min-w-0">
                        <div className="flex items-center gap-2">
                          <span
                            className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-medium ${meta.color}`}
                          >
                            <TypeIcon size={11} />
                            {meta.label}
                          </span>
                          <span className="text-xs text-zinc-400">#{item.id}</span>
                        </div>
                        <h4 className="mt-1.5 font-medium text-zinc-900 dark:text-zinc-50">{title}</h4>
                        {(item.description || item.summary) && (
                          <p className="mt-1 line-clamp-2 text-sm text-zinc-500 dark:text-zinc-400">
                            {item.description ?? item.summary}
                          </p>
                        )}
                      </div>
                    </div>
                    <div className="flex shrink-0 flex-col gap-2">
                      <button
                        onClick={() => review(item.id, "approve")}
                        disabled={busyId === item.id || bulkBusy}
                        className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-1.5 text-xs font-medium text-white transition hover:bg-emerald-500 disabled:opacity-50"
                      >
                        <CheckCircle size={13} /> 通过
                      </button>
                      <button
                        onClick={() => review(item.id, "reject")}
                        disabled={busyId === item.id || bulkBusy}
                        className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-1.5 text-xs font-medium text-red-600 transition hover:bg-red-50 disabled:opacity-50 dark:border-red-500/30 dark:hover:bg-red-500/10"
                      >
                        <XCircle size={13} /> 拒绝
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </>
        )}
      </div>
    </div>
  );
}
